server:
   port: 8888
spring:
    cloud:
        config:
            server:
                # don't decrypt values on config server
                encrypt.enabled: false
                git:
                    uri: https://github.com/SnakeDoc/SpringMicroservicesInActionConfig
                    searchPaths: licensingservice
                    