version: '2'
services:
    eurekaserver:
        image: snakedoc/tmx-eurekasvr:chapter4
        ports:
          - "8761:8761"
    configserver:
        image: snakedoc/tmx-confsvr:chapter4
        ports:
          - "8888:8888"
        environment:
            ENCRYPT_KEY: "IMSYMMETRIC"
    database:
        image: postgres:9.5
        ports:
          - "5432:5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "p0stgr@s"
            POSTGRES_DB: "eagle_eye_local"
    licensingservice:
        image: snakedoc/tmx-licensing-service:chapter4
        ports:
          - "8080:8080"
        environment:
            PROFILE: "default"
            CONFIGSERVER_URI: "http://configserver:8888"
            CONFIGSERVER_PORT: "8888"
            DATABASESERVER_PORT: "5432"
            ENCRYPT_KEY: "IMSYMMETRIC"
    organizationservice:
        image: snakedoc/tmx-organization-service:chapter4
        ports:
          - "8085:8085"
        environment:
            PROFILE: "default"
            SERVER_PORT: "8085"
            CONFIGSERVER_URI: "http://configserver:8888"
            CONFIGSERVER_PORT: "8888"
            EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
            EUREKASERVER_PORT: "8761"
            DATABASESERVER_PORT: "5432"
            ENCRYPT_KEY: "IMSYMMETRIC"
