version: '2'
services:
    eurekaserver:
        image: "${IMAGE_USER}/${IMAGE_PREFIX}eurekasvr:${IMAGE_CHAPTER}"
        ports:
          - "8761:8761"
    configserver:
        image: "${IMAGE_USER}/${IMAGE_PREFIX}confsvr:${IMAGE_CHAPTER}"
        ports:
          - "8888:8888"
        environment:
            SERVER_PORT: "8888"
            EUREKASERVER_URI: "${EUREKASERVER_URI}:${EUREKASERVER_PORT}/${EUREKASERVER_PATH}/"
            EUREKASERVER_PORT: "${EUREKASERVER_PORT}"
            ENCRYPT_KEY: "${KEY}"
    database:
        image: "postgres:9.5"
        ports:
          - "5432:5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "p0stgr@s"
            POSTGRES_DB: "eagle_eye_local"
    licensingservice:
        image: "${IMAGE_USER}/${IMAGE_PREFIX}licensing-service:${IMAGE_CHAPTER}"
        ports:
          - "8080:8080"
        environment:
            PROFILE: "default"
            SERVER_PORT: "8080"
            CONFIGSERVER_URI: "${CONFIGSERVER_URI}:${CONFIGSERVER_PORT}"
            CONFIGSERVER_PORT: "${CONFIGSERVER_PORT}"
            EUREKASERVER_URI: "${EUREKASERVER_URI}:${EUREKASERVER_PORT}/${EUREKASERVER_PATH}/"
            EUREKASERVER_PORT: "${EUREKASERVER_PORT}"
            DATABASESERVER_PORT: "${DATABASESERVER_PORT}"
            ENCRYPT_KEY: "${KEY}"
    organizationservice:
        image: "${IMAGE_USER}/${IMAGE_PREFIX}organization-service:${IMAGE_CHAPTER}"
        ports:
          - "8085:8085"
        environment:
            PROFILE: "default"
            SERVER_PORT: "8085"
            CONFIGSERVER_URI: "${CONFIGSERVER_URI}:${CONFIGSERVER_PORT}"
            CONFIGSERVER_PORT: "${CONFIGSERVER_PORT}"
            EUREKASERVER_URI: "${EUREKASERVER_URI}:${EUREKASERVER_PORT}/${EUREKASERVER_PATH}/"
            EUREKASERVER_PORT: "${EUREKASERVER_PORT}"
            DATABASESERVER_PORT: "${DATABASESERVER_PORT}"
            ENCRYPT_KEY: "${KEY}"
    organizationservice2:
        image: "${IMAGE_USER}/${IMAGE_PREFIX}organization-service:${IMAGE_CHAPTER}"
        ports:
          - "8086:8086"
        environment:
            PROFILE: "default"
            SERVER_PORT: "8086"
            CONFIGSERVER_URI: "${CONFIGSERVER_URI}:${CONFIGSERVER_PORT}"
            CONFIGSERVER_PORT: "${CONFIGSERVER_PORT}"
            EUREKASERVER_URI: "${EUREKASERVER_URI}:${EUREKASERVER_PORT}/${EUREKASERVER_PATH}/"
            EUREKASERVER_PORT: "${EUREKASERVER_PORT}"
            DATABASESERVER_PORT: "${DATABASESERVER_PORT}"
            ENCRYPT_KEY: "${KEY}"
